name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - python_module
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app for release
        run: msbuild get-parent-device.sln