name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - python_module
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app for release
        run: msbuild get-parent-device.sln -p:Configuration=Release

      - name: Build app for Debug
        run: msbuild get-parent-device.sln -p:Configuration=Debug


      - name: Compress artifacts
        uses: edgarrc/action-7z@v1
        with:
            args: 7z a -t7z -mx=9 build.7z ./Debug/ ./Release/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: w32binary
          # A file, directory or wildcard pattern that describes what to upload
          #path: ./**/get-parent-device.exe
          path: build.7z
    
